[tool.poetry]
name = "opentamp"
version = "0.1.0"
description = "Open-Source Robot Task and Motion Planning with Python!"
authors = ["Nishanth Kumar <njk@csail.mit.edu>, Dylan Hadfield-Menell <dhm@csail.mit.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<=3.11"
numpy = "*"
ipdb = "*"
numdifftools = "*"
psutil = "*"
robosuite = "*"
dm-control = "*"
h5py = "*"
gym = "*"
robodesk = "*"
osqp = "*"
sco-py = {git = "https://github.com/Algorithmic-Alignment-Lab/sco.git", branch = "main" }
torch = {version = "*"}
pandas = {version = "*"}
seaborn = {version = "*"}
imageio = {version = "*"}
mpi4py = {version = "*"}
matplotlib = {version = "*"}
gurobipy = {version = "*"}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
learning = ["torch", "pandas", "seaborn", "imageio", "mpi4py", "matplotlib", "psutil"]
gurobi = ["gurobipy"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
