; AUTOGENERATED. DO NOT EDIT.

(define (problem ff_prob)
(:domain robotics)
(:objects
r0 - Room
targ - Target
rob - Robot
domset - DomainSettings
)

(:init
(RobotInRoom rob r0 )
(RobotInRoom rob r0 ))

(:goal
(and (TaskComplete rob targ))
)
)