; AUTOGENERATED. DO NOT EDIT.

(define (problem ff_prob)
(:domain robotics)
(:objects
r0 - Room
l0 - Location
targ - Target
rob - Robot
domset - DomainSettings
)

(:init
(RobotInRoom rob r0 )
(TargetInRoom targ r0 )
(LocationInRoom l0 r0 )
(LocationInRoom l0 r0 )(TargetInRoom targ r0 )(RobotInRoom rob r0 ))

(:goal
(and (TaskComplete rob ))
)
)