; AUTOGENERATED. DO NOT EDIT.

(define (domain robotics)                  
(:requirements :strips :equality :typing)
(:types
Robot Room Wall Location Target DomainSettings - base_object)

(:predicates
(RobotInRoom ?var0 - Robot ?var1 - Room )
(LocationInRoom ?var0 - Location ?var1 - Room )
(TargetInRoom ?var0 - Target ?var1 - Room )
(RobotAtLocation ?var0 - Robot ?var1 - Location )
(RobotAtTarget ?var0 - Robot ?var1 - Target )
(TaskComplete ?var0 - Robot )
(IsMP ?var0 - Robot )
)

(:action move_to_loc_same_room
:parameters (?robot - Robot ?room - Room ?loc1 - Location ?loc2 - Location ?target - Target)       
:precondition (and (RobotInRoom ?robot ?room)(RobotAtLocation ?robot ?loc1)(LocationInRoom ?loc1 ?room)(LocationInRoom ?loc2 ?room)) 
:effect (and (RobotInRoom ?robot ?room)(RobotAtLocation ?robot ?loc2)(IsMP ?robot)(not (RobotAtLocation ?robot ?loc1))(RobotAtTarget ?robot ?target))
)

(:action complete_task
:parameters (?robot - Robot ?target - Target)  
:precondition (and (RobotInRoom ?robot ?room)(TargetInRoom ?target ?room)(RobotAtTarget ?robot ?target)) 
:effect (and (TaskComplete ?robot))
)

)